--!nonstrict
--[[
    FileName    > test.luau
    Author      > AveryArk
    Contact     > Twitter: https://twitter.com/averyark_
    Created     > 16/06/2026
--]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

const Craftsman = require("../Packages/_TestIndex/averyark_craftsman@dev/Craftsman")
const AnimationUtil = require("../Packages/_TestIndex/averyark_craftsman@dev/Craftsman/Utilities/AnimationUtil")

local test = {}


return test
